### ISSUE TITLE
Vendor Packages

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#2800]
This issue describes an upcoming feature with a bunch of related changes, which might then require dedicated issues once being implemented.

## New Basket Section for Basket Configuration

```json
    "DirectorBasketConfig": {
      "configVersion": 2,
      "vendorName": "Some Icinga Partner",
      "packageName": "Brand Name Basic Checks",
      "packageName": "Ready to use Icinga Service and Command definitions for our...",
      "packageVersion": "v1.12.324",
      "packageUuid": "a85e0404-6eef-4fe2-9750-629abd5b2427",
    }
```

### Steps

* [ ]  Refuse Baskets with an unsupported `configVersion` (v1.11)
* [x] Create a new DB table: `director_config_package`
* [ ] Populate `director_config_package`
* enforce semver (major.minor.patch) in case an (optional) version string has been provided

### Schema Changes

```sql
CREATE TABLE director_config_package (
  uuid VARBINARY(16) NOT NULL,
  version VARCHAR(11) DEFAULT NULL,
  name VARCHAR(128) NOT NULL,
  vendor VARCHAR(128) NOT NULL,
  description TEXT DEFAULT NULL,
  PRIMARY KEY (uuid),
  INDEX idx_sort_by_name (name),
  INDEX idx_sort_by_vendor_and_name (vendor, name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

### Steps
* [ ] Add `package_uuid` column to ALL object types, Icinga- and non-Icinga Objects (example given)
* [ ] Add a `readonly` column (example given)
* [ ] Storing a modified protected object will only be allowed, when a matching "global" `RestoringConfigPackageUuid` has been set at runtime
* [ ] API, CLI and Sync SHOULD also be forced to respect this rule (requirement might be discussed/dropped)
* [ ] A vendor can specify which custom variables and choices a user might be allowed to modify
* [ ] All objects in a vendor package basket are considered being `readonly` objects, unless this is being overridden at object level

### Schema Changes
```sql
ALTER TABLE icinga_host ADD COLUMN package_uuid VARBINARY(16) NOT NULL;
ALTER TABLE icinga_host ADD COLUMN protected ENUM('y', 'n') DEFAULT 'n';
ALTER TABLE icinga_host MODIFY COLUMN readonly ENUM('y', 'n') DEFAULT null;

-- ... more or less the same for all tables
```

### Steps

* [ ] Check ALL object for constraint violations, give useful error messages in case there are such
* [ ] wipe all related objects from the DB, including the `director_config_package` entry

### Steps

* [ ] Currently they do not exist, needs to be introduced as a prerequisite for related changes
* [ ] when doing this, change required_template_id to required_template_uuid

## Support Choices in Baskets

```json
"HostTemplateChoice": {
  "Check Interval": {
    "uuid": "381ee32b-d503-454f-b39b-e1e8c3591ed2",
    "object_name": "Check Interval",
    "min_required": 0,
    "max_allowed": 0,
    "required_template_uuid": "dc1323ab-4432-41d2-9c58-81f405eef1d5",
    "member_uuids": [
      "a9aa5e5-b341-44f2-0b34-d5957f39919fe"
    ],
    "removable_member_uuids": [
      "2eefd67-85dd-e4b5-c987-7faeacb9d6c59"
    ]
  }
},
```

### Steps

* [ ] Implement related basket support
* [ ] Grant fine-grained modification permissions:
* * [ ] when only `member_uuids` has been set, the Choice cannot be modified
* * [ ] when the array `removable_member_uuids` has been specified, Choice members can be extended
* * [ ] it's possible to remove members defined in `removable_member_uuids` 
* [x] new DB tables: `icinga_*_choice_option`
* [ ] `icinga_*_template_choice`: add `protect_templates = y`

### Schema Changes

```sql
-- TODO: requires uuid on icinga_*_template_choice

CREATE TABLE icinga_host_choice_option (
  choice_uuid VARBINARY(16) NOT NULL,
  template_uuid VARBINARY(16) NOT NULL,
  enforced ENUM('y', 'n') NOT NULL,
  weight mediumint(8) unsigned DEFAULT NULL,
  PRIMARY KEY (choice_uuid, template_uuid),
  UNIQUE KEY unique_order (choice_uuid,weight),
  -- KEY icinga_host_choice_member_template (template_uuid), -> pg only, auto on MySQL
  CONSTRAINT icinga_host_choice_member_choice
    FOREIGN KEY (choice_uuid)
      REFERENCES icinga_host_template_choice (uuid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
  CONSTRAINT icinga_host_choice_member_template
    FOREIGN KEY (template_uuid)
      REFERENCES icinga_host (uuid)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE icinga_service_choice_option (
  choice_uuid VARBINARY(16) NOT NULL,
  template_uuid VARBINARY(16) NOT NULL,
  enforced ENUM('y', 'n') NOT NULL,
  weight mediumint(8) unsigned DEFAULT NULL,
  PRIMARY KEY (choice_uuid, template_uuid),
  UNIQUE KEY unique_order (choice_uuid,weight),
  -- KEY icinga_service_choice_member_template (template_uuid), -> pg only, auto on MySQL
  CONSTRAINT icinga_service_choice_member_choice
    FOREIGN KEY (choice_uuid)
      REFERENCES icinga_service_template_choice (uuid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
  CONSTRAINT icinga_service_choice_member_template
    FOREIGN KEY (template_uuid)
      REFERENCES icinga_service (uuid)
      ON DELETE CASCADE
      ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

## Add default_choices to Host- and Servicetemplates

Choices are imports, and stored as such. "Slow Checks" is an option belonging to a Choice:

```json
"HostTemplate": {
    "Some Host Template": {
        "imports": [
          "Slow Checks", "Default Host"
        ],
    }
}
```

A vendor might want to set a default choice, while giving the user the possibility, to change that Choice at a template level. As of now, this would conflict with the next basket (vendor package) import.

The same basket could use as follows based on this feature:

```json
"HostTemplate": {
    "Some Host Template": {
        "imports": [
          "Default Host",
        ],
        "default_choice_uuids": [
          "f07a54ac-1da9-4fb0-8f40-b65480b85e30": [],
          "12e2a1a0-6a91-4add-a6b9-f5ce72b50ad4": ["0a23afc1-0824-4863-a163-34fbd469fb67"]
        ],
    }
}
```

### Tasks

* [ ] Schema changes: add default choice relation tables (like inheritance)
* [ ] Provide the possibility to set `enforced = n` for every choice uuid defined in default_choices
* [ ] Grant fine-grained modification permissions:
* * [ ] when only `imports` has been set, the Choice cannot be modified for a protected object
* * [ ] for every member of the `default_choice_uuids` dictionary (keys are Choice-UUIDs), users are allowed to change the default choice on the (protected) template
* * [ ] choice options, whose uuid has been provided in the `removable_member_uuids` choice-specific arrays, can be removed by the user. A related DB column (`import_disabled` or similar) has to be defined

### Allow to delete objects with a basket

```json
"DataList": {
    "Old obsolete List": {
        "uuid": "c555ca0e-3207-4d11-b186-9a38a87199a3",
        "list_name": "Old obsolete List",
        "updateMode": "delete",
    }
}
```

## Implement default_vars

The main purpose of this task is allowing a vendor to specify default thresholds for checks, while allowing the user to still change those defaults directly on the template.

```sql
"ServiceTemplate": {
    "Some Check": {
            "default_vars": {
              "disk_free_critical_percent": "10%"
            },
            "vars": {
                "verbose": true",
            }
        }
    }
}
```

### Tasks

* [ ] implement and model similar to default_choices
* [ ] form fields matching default_vars should be available to the user on protected/read-only objects

### Allow to merge list entries

The default update mode when restoring a basket is "replace". For unprotected
lists (or when filling a list from multiple sources) the "merge" update mode
comes in handy:

```json
"DataList": {
    "System Lifecycle": {
        "entries": [{
            "entry_name": "deployment",
            "entry_value": "System being Deployment",
        }, {
            "entry_name": "ready",
            "entry_value": "System is ready",
        }, {
            "entry_name": "live",
            "entry_value": "System is live",
        }
        ],
        "list_name": "System Lifecycle",
        "read-only": false,
        "updateMode": "merge"
    }
}
```

### Allow to delete specific list entries

```json
"DataList": {
    "System Lifecycle": {
        "entries": [{
            "entry_name": "live",
            "entry_value": "System is live",
        }],
        "removeEntries": [
           "deployment",
           "ready"
        ]
        "list_name": "System Lifecycle",
        "updateMode": "merge"
    }
}
```

Given the use-case with multiple sources filling a common list, one
source might want to explicitly remove a specific list entry.

## Implement Choice priority

Choices are appended AFTER all other imports. It should be possible to tweak their order by changing their weight. This has already been provided with the schema changes provided above
